version: 2
jobs:
  build_development:
    machine:
        enabled: true
        post:
            - pyenv global 2.7.12
    working_directory: ~/edx-platform
    parallelism: 4
    artifacts:
      - "reports"
      - "test_root/log"
    steps:
      - checkout
      - run:
          name: apt-get update
          command: 'sudo apt-get update'
      - run:
          name: install needed apt packages
          command: 'DEBIAN_FRONTEND=noninteractive sudo apt-get install -q -y $(cat requirements/system/ubuntu/apt-packages.txt)'
      - run:
          name: nmp install
          command: 'npm install'
      - run:
           name: apt-get install python
           command: 'sudo apt-get install python-dev --fix-missing'
      - run:
          name: pip install setuptools
          command: 'pip install setuptools'
      - run:
          name: pip install paver.txt
          command: 'pip install --exists-action w -r requirements/edx/paver.txt'
      - run:
          name: install pre requirements
          command: 'pip install --exists-action w -r requirements/edx/pre.txt'
      - run:
          name: install github requirements
          command: 'pip install --exists-action w -r requirements/edx/github.txt'
      - run:
          name: install local requirements
          command: 'pip install --exists-action w -r requirements/edx/local.txt'
      - run:
          name: install pbr
          command: 'pip install  --exists-action w pbr==0.9.0'
      - run:
          name: install base requirements
          command: 'pip install --exists-action w -r requirements/edx/base.txt'
      - run:
          name: install testing requirements
          command: 'pip install --exists-action w -r requirements/edx/testing.txt'
      - run: 
          name: install post if required
          command: 'if [ -e requirements/edx/post.txt ]; then pip install --exists-action w -r requirements/edx/post.txt ; fi'
      - run:
          name: install coveralls
          command: 'pip install coveralls==1.0'
      - run:
          name: output install packages to console, help with debug
          command: 'pip freeze'
      - run:
          name: run all tests
          command: './scripts/all-tests.sh'
          no_output_timeout: 20m
      - store_artifacts:
          path: reports
          destination: test_reports
      - store_test_results:
          path: test_root/log



workflows:
  version: 2
  build:
    jobs:
      - build_development:
          filters:
            branches:
              only: proversity/development
  
              