version: 2
jobs:
  build_development:
    machine: true
    working_directory: ~/edx-platform
    parallelism: 1
    steps:
      - checkout
      - run:
          name: apt-get update
          command: 'sudo apt-get update'
      - run:
           name: apt-get install python
           command: 'sudo apt-get install python-dev --fix-missing'
      - run:
          name: pip install awscli
          command: 'pip install awscli'
      - run:
          name: set region
          command: 'aws configure set default.region eu-west-1'
      - run:
          name: apt-get update
          command: 'STAGING_SEC_GROUP=$STAGING_SEC_GROUP /bin/bash build_and_deploy.sh development'
      

workflows:
  version: 2
  build:
    jobs:
      - build_development:
          filters:
            branches:
              only: proversity/development
