version: 2
jobs:
  build_development:
    machine:
        enabled: true
    working_directory: ~/edx-platform
    docker:
      - image: circleci/python:2.7.10
    artifacts:
      - "reports"
      - "test_root/log"
    steps:
      - checkout
      - run:
          name: install needed apt packages
          command: 'DEBIAN_FRONTEND=noninteractive sudo apt-get install -q -y $(cat requirements/system/ubuntu/apt-packages.txt)'
      - run:
          name: nmp install
          command: 'npm install'
      - run:
          name: apt-get update
          command: 'sudo apt-get update'
      - run:
           name: apt-get install python
           command: 'sudo apt-get install python-dev --fix-missing'
      - run:
          name: pip install setuptools
          command: 'pip install setuptools'
      - run:
          name: pip install paver.txt
          command: 'pip install --exists-action w -r requirements/edx/paver.txt'
      - run:
          name: install pre requirements/edx/paver
          command: 'pip install --exists-action w -r requirements/edx/pre.txt'
      - run:
          name: install github requirements/edx/paver
          command: 'pip install --exists-action w -r requirements/edx/github.txt'
      - run:
          name: install local requirements/edx/github
          command: 'pip install --exists-action w -r requirements/edx/local.txt'
      - run:
          name: install pbr
          command: 'pip install  --exists-action w pbr==0.9.0'
      - run:
          name: install base requirements
          command: 'pip install --exists-action w -r requirements/edx/base.txt'
      - run:
          name: install paver requirements
          command: 'pip install --exists-action w -r requirements/edx/paver.txt'
      - run:
          name: install testing requirements
          command: 'pip install --exists-action w -r requirements/edx/testing.txt'
      - run: 
          name: install post if required
          command: 'if [ -e requirements/edx/post.txt ]; then pip install --exists-action w -r requirements/edx/post.txt ; fi'
      - run:
          name: install coveralls
          command: 'pip install coveralls==1.0'
      - run:
          name: output install packages to console, help with debug
          command: 'pip freeze'
      - run:
          name: run all tests
          command: './scripts/all-tests.sh'
          no_output_timeout: 20m

  build_master:
     machine:
       enabled: false
     working_directory: ~/edx-platform
     steps:
       - run:
           name: testing
           command: 'ls -la' 


workflows:
  version: 2
  build:
    jobs:
      - build_development:
          filters:
            branches:
              only: proversity/development
            timeout: 900
      - build_master:
          filters:
            branches:
              only: master
  
              