version: 2
jobs:
  build:
    machine: true
    working_directory: ~/edx-platform
    parallelism: 1
    steps:
      - checkout
      - run:
          name: apt-get update
          command: 'STAGING_SEC_GROUP=$STAGING_SEC_GROUP /bin/bash build_and_deploy.sh'
      

workflows:
  version: 2
  build:
    jobs:
      - build_development:
          filters:
            branches:
              only: proversity/development
